plugins {
    id 'com.gradleup.shadow' version '9.6.1'
}

configurations {
    shadowCommon
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.architectury.minecraft}"
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation "dev.architectury:architectury:${rootProject.architectury_api_version}:dev"
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets {
    main {
        resources {
            srcDir "src/generated/resources"
        }
    }
}

jar {
    archiveClassifier = 'raw'
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn jar
    mainSpec.sourcePaths.clear()
    from zipTree(jar.archiveFile)
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}
