modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "colorful_redstone_lamps"
version = "${version}"
displayName = "Colorful Redstone Lamps"
authors = "Pasuki"
description = '''
Colorful Redstone Lamps expands Minecraft with vibrant redstone lamps in many colors.
Craft each variant to match your builds while keeping classic redstone behavior: lamps light up when powered.
It also adds inverted lamps, which behave opposite to normal lamps and turn off when powered.
'''
#logoFile = ""

[[dependencies.colorful_redstone_lamps]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.88,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorful_redstone_lamps]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.colorful_redstone_lamps]]
modId = "architectury"
type = "required"
versionRange = "[21.1.11,21.2)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "colorful_redstone_lamps.mixins.json"
